//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbOkul
{
    using System;
    using System.Collections.Generic;
    
    public partial class ders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ders()
        {
            this.ogrenci_ders = new HashSet<ogrenci_ders>();
            this.ogretmen = new HashSet<ogretmen>();
        }
    
        public int did { get; set; }
        public string dadi { get; set; }
        public string dkodu { get; set; }
        public Nullable<int> kredi { get; set; }
        public Nullable<int> bid { get; set; }
    
        public virtual bolum bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ogrenci_ders> ogrenci_ders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ogretmen> ogretmen { get; set; }
    }
}
