//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbOkul
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenci_ders
    {
        public int ono { get; set; }
        public int did { get; set; }
        public Nullable<double> nott { get; set; }
    
        public virtual ders ders { get; set; }
        public virtual ogrenci ogrenci { get; set; }
    }
}
