//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbOkul
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogretmen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ogretmen()
        {
            this.ders = new HashSet<ders>();
        }
    
        public int oid { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string dyeri { get; set; }
        public Nullable<int> bid { get; set; }
    
        public virtual bolum bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ders> ders { get; set; }
    }
}
